---
- name: Install Apache HTTPD on CentOS/RHEL
  hosts: my_ec2  # Replace with your group or IP
  become: yes  # Run as root
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present
       
    - name: Start and enable httpd service
      systemd:
        name: httpd
        state: started
        enabled: yes
 
