---
- name: Install NGINX on EC2 instance
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Update the system
      yum:
        name: '*'
        state: latest

    - name: Install NGINX
      amazon.aws.amazon_linux_extras:
        name: "nginx1"
        state: present

    - name: Start NGINX service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: yes
